# Generated by Django 3.2.14 on 2022-12-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='creating_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
