# Generated by Django 3.2.14 on 2022-12-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_alter_catagory_creating_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creating_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
